name: Deploy to Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: 
                Checkout code
              uses: actions/checkout@v2
            
            - name: 
                Connect to server
              uses: appleboy/ssh-action@master
              with:
                    host: 106.15.170.182
                    username: aplus
                    password: ${{ secrets.SERVER_PASSWORD }}

            - name: 
                Pull latest code
              run: git clone https://github.com/Springrx/location_server.git

            - name: Install dependencies
              run: npm install

            - name: Run code
              run: npm run dev
